// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZLvr6bVz9Goc6PbKYpLVIQm-XF1rywPA',
    appId: '1:526715549752:web:1405938b7d7ffb2a678ecd',
    messagingSenderId: '526715549752',
    projectId: 'gradhub-126e3',
    authDomain: 'gradhub-126e3.firebaseapp.com',
    storageBucket: 'gradhub-126e3.firebasestorage.app',
    measurementId: 'G-HWZY3LQRD2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6tnB5_6pMErFDZW_-kncj1Kx7gKgG3TU',
    appId: '1:526715549752:android:421a5f04add83079678ecd',
    messagingSenderId: '526715549752',
    projectId: 'gradhub-126e3',
    storageBucket: 'gradhub-126e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVpFCzs1ikYhPcpE5GAec58MJJVAZTtcE',
    appId: '1:526715549752:ios:a1bacac307e969c8678ecd',
    messagingSenderId: '526715549752',
    projectId: 'gradhub-126e3',
    storageBucket: 'gradhub-126e3.firebasestorage.app',
    iosBundleId: 'com.example.graduationManagementIdeaSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVpFCzs1ikYhPcpE5GAec58MJJVAZTtcE',
    appId: '1:526715549752:ios:a1bacac307e969c8678ecd',
    messagingSenderId: '526715549752',
    projectId: 'gradhub-126e3',
    storageBucket: 'gradhub-126e3.firebasestorage.app',
    iosBundleId: 'com.example.graduationManagementIdeaSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZLvr6bVz9Goc6PbKYpLVIQm-XF1rywPA',
    appId: '1:526715549752:web:f7ad0b4d337ca87d678ecd',
    messagingSenderId: '526715549752',
    projectId: 'gradhub-126e3',
    authDomain: 'gradhub-126e3.firebaseapp.com',
    storageBucket: 'gradhub-126e3.firebasestorage.app',
    measurementId: 'G-C8VTHKJ7WZ',
  );
}
